name: Sign APK and Upload Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sign-apk:
    name: Sign APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Android SDK and apksigner
        run: |
          sudo apt update
          sudo apt install -y zipalign
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d android-sdk
          yes | android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk --licenses
          android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk "build-tools;34.0.0"
          echo "PATH=$PATH:$PWD/android-sdk/build-tools/34.0.0" >> $GITHUB_ENV

      - name: Find Unsigned APK
        id: find_apk
        run: |
          APK_PATH=$(find . -type f -name "*unsigned*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "No unsigned APK found."
            exit 1
          fi
          echo "Found APK: $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

      - name: Decode and Save Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.jks

      - name: Align APK (zipalign) **before signing**
        run: |
          ZIPALIGNED_APK="${APK_PATH//unsigned/foss}"
          android-sdk/build-tools/34.0.0/zipalign -v 4 "$APK_PATH" "$ZIPALIGNED_APK"
          echo "SIGNED_APK=$ZIPALIGNED_APK" >> $GITHUB_ENV

      - name: Sign APK with apksigner (v2/v3/v4 signing)
        run: |
          android-sdk/build-tools/34.0.0/apksigner sign --ks my-release-key.jks \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_ALIAS_PASSWORD }} \
            --out "${{ env.SIGNED_APK }}" "${{ env.SIGNED_APK }}"

      - name: Upload Signed APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Signed-APK
          path: ${{ env.SIGNED_APK }}
          retention-days: 7