name: Sign APK and Upload Artifact

on:
  push:
    branches:
      - main  # Runs on commits to the main branch
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  sign-apk:
    name: Sign APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find Unsigned APK
        id: find_apk
        run: |
          APK_PATH=$(find . -type f -name "*unsigned*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "No unsigned APK found."
            exit 1
          fi
          echo "Found APK: $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

      - name: Decode and Save Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.jks

      - name: Sign the APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore my-release-key.jks \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_ALIAS_PASSWORD }}" \
            "$APK_PATH" ${{ secrets.KEY_ALIAS }}

      - name: Rename Signed APK
        run: |
          SIGNED_APK="${APK_PATH//unsigned/foss}"  # Replace "unsigned" with "Foss"
          mv "$APK_PATH" "$SIGNED_APK"
          echo "SIGNED_APK=$SIGNED_APK" >> $GITHUB_ENV

      - name: Upload Signed APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Signed-APK
          path: ${{ env.SIGNED_APK }}
          retention-days: 7  # Keep artifact for 7 days