name: Sign APK and Upload Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sign-apk:
    name: Sign APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find Unsigned APK
        id: find_apk
        run: |
          APK_PATH=$(find . -type f -name "*unsigned*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "No unsigned APK found."
            exit 1
          fi
          echo "Found APK: $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

      - name: Decode and Save Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.jks

      - name: Sign APK with apksigner
        run: |
          SIGNED_APK="${APK_PATH//unsigned/Foss}"
          cp "$APK_PATH" "$SIGNED_APK"
          apksigner sign --ks my-release-key.jks \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_ALIAS_PASSWORD }} \
            --out "$SIGNED_APK" "$SIGNED_APK"
          echo "SIGNED_APK=$SIGNED_APK" >> $GITHUB_ENV

      - name: Align the APK (zipalign)
        run: |
          ZIPALIGNED_APK="${{ env.SIGNED_APK }}-aligned.apk"
          zipalign -v 4 "${{ env.SIGNED_APK }}" "$ZIPALIGNED_APK"
          mv "$ZIPALIGNED_APK" "${{ env.SIGNED_APK }}"

      - name: Upload Signed APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Signed-APK
          path: ${{ env.SIGNED_APK }}
          retention-days: 7